name: CI/CD pipeline

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: docker-ci-cd-pipeline

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define tags
        id: meta
        run: |
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_OUTPUT
          echo "LATEST_TAG=latest" >> $GITHUB_OUTPUT
          echo "BUILD_TAG=build-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Build image (no push) for tests
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:ci-test .

      - name: Run containerized tests
        run: |
          bash tests/test_app.sh ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:ci-test

      - name: Build and push with tags
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.LATEST_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.BUILD_TAG }}

      - name: Output pushed tags
        run: |
          echo "Pushed tags:"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.LATEST_TAG }}"
          echo "${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.BUILD_TAG }}"
